### ISSUE TITLE
Let's try something - Elaborate tests

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/twu-biblioteca-bal#1]
https://github.com/bsandhu1920/twu-biblioteca-bal/blob/860c48124ae1edd05651933298ec0c6104a4360f/test/com/twu/biblioteca/MenuTests.java#L52-L56

The testing is a bit too _minute_. This may sound contradictory to the advices about having many tests, so allow me to try and explain.

I said before that our tests should show that for a given input, we always get the same output, every time. This is still true. What I did not mention but should have, is that our tests should also be a form of documentation on the business-behaviour of our application. Testing that a String number is a number is useful, but on its own it does not mean enough to developers. Let's start with the naming:

A common convention with test names is "should[ExpectedBehaviour]When[CertainInput]Given()". In your case, the test is "numericalInputIsNumber()", and it just checks exactly that. How about "shouldReturnInvalidOptionMessageWhenInputIsNotANumber()", instead? Now the test is a bit more meaningful. As a developer, when I glance at this test name, I will now know how this certain input will affect the program. This will mean you'll have to change your tests (whether it be combine, delete, add) up a bit, but in return your tests will tell us a lot more. Try that.

**Comment by bsandhu1920** [comment]
Okay that makes a bit more sense, I had a feeling that the tests were going too in depth but that was because I wanted to ensure there was a test for each method. 

I'll have a got at this.

**Comment by bsandhu1920** [comment]
Hi Eugene I've made some adjustments, please have a look when you can. I'll continue on with the rest of it till then.

**Comment by etangtw** [comment]
Yep. On the right track. Good one. I'll have a further look tomorrow hopefully.
