### ISSUE TITLE
Choose your own adventure - More IDE-dependent files

### ISSUE THREAD

**Issue by etangtw** [bsandhu1920/twu-biblioteca-bal#4]
Having glanced at the README, I can see now that there's a bit of a contradiction. The README recommends adding in .idea whereas I do not. This is a case of two voices of authorities having differing opinions on a matter. The course of action for you on this will be to weigh up the merits of each approach then choose either option. There's no wrong choice here. I personally wouldn't for the reasons listed before but you may disagree and you're allowed to.

**Comment by bsandhu1920** [comment]
Hi Eugene this is something I had done before I was given feedback for the first assignment. I'm currently going through the process of fixing up the and refactoring the issues that became present during the first.

Thanks!

**Comment by etangtw** [comment]
No worries. It can still be your choice on the matter. Having seen the README's reason for including it:

> (Dont forget to add the hidden .idea folder, as it will make opening your project in Intellij easier.)

...I don't believe the trade-off for making opening projects easier in IntelliJ to be a reasonable compromise.

**Comment by bsandhu1920** [comment]
That README was the one provided with the original project, I have fixed this up and removed the additional project files. I would agree with you on this one, given that the user could use any IDE for a project like this.
